### ISSUE TITLE
Bootstrap3 Input Groups

### ISSUE THREAD

**Issue by fran-worley** [apotonick/formular#1]
See http://getbootstrap.com/components/#input-groups for official docs, but to generate an input group, you need the following markup:
```html
<div class="form-group">
  <div class="input-group">
    <span class="input-group-addon">Content</span>
    <input type="text" name="text" class="form-control">
  </div>
</div>
```
Currently using formular, if I do this:
```slim
  .form-group
    .input-group
      span class="input-group-addon" Title
      = f.input :title, placeholder: "Title"
```
I get this:
```html
<div class="form-group">
  <div class="input-group">
    <span class="input-group-addon">Title</span>
    <div class="form-group">
      <input id="form_title" class="form-control" type="text" value="" placeholder="Title" name="title">
    </div>
  </div>
</div>
```
The "form-group" div surrounding the input causes the input group to render incorrectly. 

The easiest fix would be to provide an option to disable the wrapper e.g.
`f.input :title, wrapper: false`
In light of the comment below, this is not the preferred solution to this.

**Comment by fran-worley** [comment]
Or alternatively (and possibly cleaner) be able to render just the input field e.g. 
```slim
.form-group
  .input-group
    span class="input-group-addon" Title
    = f.text_field :title, placeholder: "Title"
```
Would produce the desired html:
```html
<div class="form-group">
  <div class="input-group">
    <span class="input-group-addon">Title</span>
    <input id="form_title" class="form-control" type="text" value="" placeholder="Title" name="title">
  </div>
</div>
```

**Comment by apotonick** [comment]
Good point. The main question here is, what is the most common use case. One of the things I dislike about both Rails form helpers and SimpleForm is that the APIs are incredibly complex. 

In Formular, I wanted to distill the API so it covers what people do on an every day basis, with the ability to suppress certain things, etc. via options. To go with your example, most devs would probably want the helper to produce "widget" markup, meaning with `.form-group`, label, etc.

This is an assumption I make without any heuristics haha. So, in turn, that'll mean we should probably go with `wrapper: false` or `widget: false` or `group: false` to turn off "convenience mode". Not sure if I'd like a separate method here better, I actually don't think so, since you still want Formular to do some extra work for you even when just rendering a simple `<input>` (e.g. computing an `"id"=".."`).

**Comment by fran-worley** [comment]
That solution would make me 👍. Thank you!

**Comment by fran-worley** [comment]
I only suggested the separate method because it is more explicit and I assumed that formulars input method called other methods under the hood so it wouldn't be anymore code.  Now I see that's not the case, options is easy and equally clear. 
If you want to stay in line with simple form go with wrapper as that's what they use. The also let you pass additional HTML options to the input via :wrapper_html option.
