### ISSUE TITLE
Gem release

### ISSUE THREAD

**Issue by carlosipe** [apotonick/formular#8]
Are you thinking in releasing the gem? The one that is on rubygems (0.0.1) has nothing on lib directory but version.rb

**Comment by apotonick** [comment]
I will release it when I feel the API is stable, the capturing works for most template engines, and when Bootstrap and Foundation are properly supported. Otherwise, I will end up getting a hundred emails every day from angry users telling me how poorly the gem is maintained. A learning from my past, sorry. :stuck_out_tongue_winking_eye:
